file1 = open('a.txt', 'r', encoding='utf-8')
file_lines1 = file1.readlines()
print(file_lines1)
file1.close()
file2 = open('b.txt', 'r', encoding='utf-8')
file_lines2 = file2.readlines()
print(file_lines2)
file2.close()
new_file = open('村上春树合集.txt', 'w', encoding='utf-8')
new_file.writelines(file_lines1)
new_file.writelines('\n')
new_file.writelines(file_lines2)
new_file.close()