"""
图文样式配置项:ItemStyleOpts
文字样式配置项:TextStyleOpts
标签配置项:LabelOpts
线样式配置项:LineStyleOpts
3D线样式配置项:Line3DEffectOpts
分割线配置项:SplitLineOpts
标记点数据项:MarkPointItem
标记点配置项:MarkPointOpts
标记线数据项:MarkLineItem
标记线配置项:MarkLineOpts
标记区域数据项:MarkAreaItem
标记区域配置项:MarkAreaOpts
涟漪特效配置项:EffectOpts
区域填充样式配置项:AreaStyleOpts
分隔区域配置项:SpliAreaOpts
次级刻度配置项:MinorTickOpts
次级分割线配置项:MinorSplitLineOpts
"""