# -*- coding: utf-8 -*-
"""Loading Data - EXERCISE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1974GfFEi9Q9kowKa2KGwo_cc8Ddc57p9

---
# Crash Course Python for Data Science  - Intro to Pandas
---
# 01 - Loading Data
---

##STOP! BEFORE GOING ANY FURTHER...

1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to something else, so you can differenciate it from the workshop notes. For example, put your name at the beggining: "Grace_Pandas Loading Data-EXERCISE".

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and save for your own archives. You can come back to it as many times as you like to practice again! Be sure to do this for ***every*** exercise!

Remember, this exercises are open book, open neighbour, open everything! Try to do them on your own before looking at the solution samples. Join the slack channel to ask your questions. I will be in the channel too!

### Import pandas with the `pd` alias.
"""

import pandas as pd
print('pandas imported!')

"""### Import the data in the CSV file.
Today you'll be working with some GDP data. You can find the data [here](https://raw.githubusercontent.com/axrd/datasets/master/gdp.csv).
"""

df = pd.read_csv("https://raw.githubusercontent.com/axrd/datasets/master/gdp.csv")

"""### Print out the first 7 rows."""

### YOUR CODE GOES HERE ###
print(df.head(7))

#@title Double click here for a sample solution

df.head(7)

"""### Print out the last 3 rows."""

### YOUR CODE GOES HERE ###
df.tail(3)

#@title Double click here for a sample solution

df.tail(3)

"""### What is the shape of the DataFrame?"""

### YOUR CODE GOES HERE ###
df.shape

#@title Double click here for a sample solution

df.shape

"""### What is the data type of each column/feature?
Hint: We didn't cover this, Google it!  

Hint 2: Columns and features are interchangeable when talking about DataFrames or tabular data in general. 
"""

### YOUR CODE GOES HERE ###
df.dtypes

#@title Double click here for a sample solution

df.dtypes

"""### Rename the column `Counry` to `Country`."""

### YOUR CODE GOES HERE ###
df = df.rename(columns={"COUNRY": "COUNTRY"})

#@title Double click here for a sample solution

df = df.rename(columns={"COUNRY": "COUNTRY"})

"""### Verify the change persisted!"""

### YOUR CODE GOES HERE ###
df.columns

#@title Double click here for a sample solution

df.columns

"""### Well done!
---

The question below is _optional_. Only tackle it after you've completed the rest of the exercise!

### STRETCH: Tying it back to Lesson 01...

*  What is the max GDP?
*  Min GDP?
*  Median GDP?
*  Standard Deviation of GDP?
"""

### YOUR CODE GOES HERE ###
print('Max GDP is ', df['GDP (BILLIONS)'].max())
print('Min GDP is ', df['GDP (BILLIONS)'].min())
print('Median GDP is ', df['GDP (BILLIONS)'].median())
print('Standard Deviation of GDP is ', df['GDP (BILLIONS)'].std())

#@title Double click here for a sample solution

print('Max GDP is ', df['GDP (BILLIONS)'].max())
print('Min GDP is ', df['GDP (BILLIONS)'].min())
print('Median GDP is ', df['GDP (BILLIONS)'].median())
print('Standard Deviation of GDP is ', df['GDP (BILLIONS)'].std())