# -*- coding: utf-8 -*-
"""Python Lists & Loops - EXERCISE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-pmTAOLjcYFV2SR0yGYWOnuC_8JkXjCp

---
#Crash Course Python for Data Science - Intro to Python
---
# 02 and 03 - Python Lists & Loops
---

##STOP! BEFORE GOING ANY FURTHER...


1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to something else, so you can differenciate it from the workshop notes. For example, put your name at the beggining: "Grace_Python Lists and Loops -EXERCISE".

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and save for your own archives. You can come back to it as many times as you like to practice again! Be sure to do this for ***every*** exercise!

Remember, this exercises are open book, open neighbour, open everything! Try to do them on your own before looking at the solution samples. Join the slack channel to ask your questions. I will be in the channel too!

## Part 1: Lists

### Use the provided lists to answer the questions and prompts.
Make sure to run the cell so the lists are declared with their corresponding values.
"""

heights = [184, 177, 190, 188, 159, 166]
weights = [84.5, 81.8, 86.1, 92.2, 69.6, 72.0 ]
names = ['John', 'Ryan', 'Bobby', 'Pete', 'Esther', 'Jane']

"""### 1.1 Create a new empty list named "BMI"."""

### YOUR CODE GOES HERE ###
BMI = []

#@title Double click here for a sample solution

BMI= []

"""### 1.2 Combine the three lists into a new list where each element is a person's name, weight, and height. Call it `person_data`."""

### YOUR CODE GOES HERE ###
person_data = []
for i,j,k in zip(names,weights,heights):
    person_data.append([i,j,k])
print(person_data)

#@title Double click here for a sample solution

person_data = [ [i, j, k] for i, j, k in zip(names, weights, heights)]
print(person_data)

# Or

person_data = []
for i, j , k in zip(names, weights, heights):
  person_data.append([i,j,k])

person_data

"""### 1.3 Retrieve the last element of `person_data`."""

### YOUR CODE GOES HERE ###
print(person_data[-1])

#@title Double click here for a sample solution

person_data[-1]

"""### 1.4 Retrieve the 2nd and 3rd elements of `person_data`."""

### YOUR CODE GOES HERE ###
print(person_data[1:3])

#@title Double click here for a sample solution

person_data[1:3] # Considering the first element as index[0]

"""### 1.5 Change the 1st element of `person_data`: increase weight to 84.9. Keep the other values unchanged."""

### YOUR CODE GOES HERE ###
print(person_data[0])

#@title Double click here for a sample solution

person_data[0][1] =  person_data[0][1] + 0.4
person_data[0]

"""### 1.6 Add another person, Samantha, to `person_data`. Her height is 162 cm and her weight is 51.3 kg. """

### YOUR CODE GOES HERE ###
person_data.append(['Samantha', 51.3, 162])
print(person_data)

#@title Double click here for a sample solution

person_data.append(['Samatha', 51.3, 162])
person_data

"""## Part 2: Loops

### 2.1 Explain a for loop in your own words.

*Double click this Text Cell to write your answer below* <br>
Answer:
"""

#@title Double click here for a sample solution

# Is what we use when we want to iterate a task over a list of elements, and we are not worried about slow execution...
# Otherwise, we'd use NumPy

"""### 2.2 Use a for loop to calculate the BMI of each person.
>$\frac{Weight(kg)}{Height(m)^2} = BMI$  
"""

### YOUR CODE GOES HERE ###
for i in person_data:
    w = i[1]
    h = i[2] / 100
    BMI = round(w / (h * h))
    print(f'{i[0]}的BMI为{BMI}')

#@title Double click here for a sample solution

for i, element in enumerate(person_data):
  w = person_data[i][1] # weith
  h = (person_data[i][2])/100 # height convert to m
  bmi = (round(w/(h*h))) # add to list
  print('The BMI of ' + person_data[i][0] + ' is ' + str(bmi)) # print each iteration

"""### 2.2 BONUS: Do it using list comprehension."""

### YOUR CODE GOES HERE ###
for i in person_data:
  BMI = round(i[1] / ((i[2]/100 * i[2]/100)))
  print(f'{i[0]}的BIM为{BMI}')

#@title Double click here for a sample solution

bmi = [[(round(person_data[i][1]/((person_data[i][2])/100)**2))] for i, element in enumerate(person_data)]
print(bmi)