# -*- coding: utf-8 -*-
"""Indexing & Subsetting DFs - EXERCISE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17BbbMSj9bNH-pKxCFtlB5NcbU2yq0e8W

---
# Crash Course Python for Data Science - Intro to Pandas
---
# 02 - Indexing & Subsetting DataFrames
---

##STOP! BEFORE GOING ANY FURTHER...

1. Click "File" at the top.
2. Then, "Save a Copy in Drive."
3. Change the file name to something else, so you can differenciate it from the workshop notes. For example, put your name at the beggining: "Grace_Pandas Indexing&Subsetting-EXERCISE".

Now you have a copy of this notebook in your Drive account. This is the copy you'll edit and save for your own archives. You can come back to it as many times as you like to practice again! Be sure to do this for ***every*** exercise!

Remember, this exercises are open book, open neighbour, open everything! Try to do them on your own before looking at the solution samples. Join the slack channel to ask your questions. I will be in the channel too!

### Import pandas
"""

import pandas as pd
print('pandas imported!')

"""### Read in your data
Your dataset can be found [here.](https://raw.githubusercontent.com/axrd/datasets/master/tipdata.csv)
Import it and return the first 5 rows:
"""

### YOUR CODE GOES HERE ###
read_csv = pd.read_csv("tipdata.csv")
print(read_csv.head(5))

#@title Double click here for a sample solution

df = pd.read_csv('tipdata.csv')
df.head(5)
"""### What is the shape of the DataFrame?"""

### YOUR CODE GOES HERE ###
print(read_csv.shape)

#@title Double click here for a sample solution

df.shape

"""### Get specific values"""

# What is the gender of the server in the 41st entry?

### YOUR CODE GOES HERE ###
print(read_csv.iloc[[41], [3]])

# What is the gender of the server in the 41st entry?
#@title Double click here for a sample solution

df.iloc[[41],[3]]

# Was the 22nd entry seated in a smoking section??

### YOUR CODE GOES HERE ###
print(read_csv.iloc[[22], [4]])

#@title Double click here for a sample solution

# Was the 22nd entry seated in a smoking section?
df.iloc[[22], [4]]

"""### Get a range of values"""

# Return the last 20 entries

## YOUR CODE GOES HERE ###
print(read_csv.tail(20))

# Return the last 20 entries.
#@title Double click here for a sample solution

df.tail(20)

# Return entries 25 through 50

### YOUR CODE GOES HERE ###
print(read_csv[25:51])

#@title Double click here for a sample solution

# Return entries 25 through 50.
df[25:51]

"""### Filtering and subsetting:"""

# Return all the entres where the size is greater than 2.

### YOUR CODE GOES HERE ###
print(read_csv[read_csv['size'] > 2])

#@title Double click here for a sample solution

# Return all the entries where the size is greater than 2.
df[df['size'] > 2]

# Create a Dataframe consisting only of data for Fridays.
# Hint: You should have 19 values.


### YOUR CODE GOES HERE ###
read_csv_friday = read_csv[read_csv['day'] == 'Fri']
print(read_csv_friday)

#@title Double click here for a sample solution

# Create a DataFrame consisting only of data for Fridays.
# Hint: You should have 19 values.

df_fridays = df[df['day'] == 'Fri']
df_fridays

"""### Well done! Make sure your save your work. See you on the next notebook. - G



---


"""